site_name: "Recul du trait de côte : indicateurs et enjeux"
nav:
  - Contexte: index.md
  - Méthodologie: methodologie.md
  - Dictionnaire: dictionnaire.md
  - À propos: about.md

theme:
  name: readthedocs
  locale: fr
